Fixing hadolint errors

diff --git a/smoove/Dockerfile_latest b/smoove/Dockerfile_latest
--- a/smoove/Dockerfile_latest
+++ b/smoove/Dockerfile_latest
@@ -12,18 +12,26 @@ LABEL org.opencontainers.image.documentation=https://getwilds.org/
 LABEL org.opencontainers.image.source=https://github.com/getwilds/wilds-docker-library
 LABEL org.opencontainers.image.licenses=MIT
 
+# Set the shell option to fail if any command in a pipe fails
+SHELL ["/bin/bash", "-o", "pipefail", "-c"]
+
 # Set environment variables for non-interactive installation
 ENV DEBIAN_FRONTEND=noninteractive
 
 # Update package list and install dependencies
-RUN apt-get update && apt-get install -y \
-    wget \
-    curl \
-    bzip2 \
-    ca-certificates \
-    && rm -rf /var/lib/apt/lists/*
+RUN apt-get update \
+  && WGET_VERSION=$(apt-cache policy wget | grep Candidate | awk '{print $2}') \
+  && CURL_VERSION=$(apt-cache policy curl | grep Candidate | awk '{print $2}') \
+  && BZIP2_VERSION=$(apt-cache policy bzip2 | grep Candidate | awk '{print $2}') \
+  && CACERT_VERSION=$(apt-cache policy ca-certificates | grep Candidate | awk '{print $2}') \
+  && apt-get install -y --no-install-recommends \
+  wget="${WGET_VERSION}" \
+  curl="${CURL_VERSION}" \
+  bzip2="${BZIP2_VERSION}" \
+  ca-certificates="${CACERT_VERSION}" \
+  && rm -rf /var/lib/apt/lists/*
 
 # Download and install smoove binary
 WORKDIR /usr/local/bin
-RUN wget https://github.com/brentp/smoove/releases/download/v0.2.8/smoove && \
+RUN wget -q https://github.com/brentp/smoove/releases/download/v0.2.8/smoove && \
     chmod +x smoove
